add backlight-related config

diff --git a/overlay/bin/desktop-spooler b/overlay/bin/desktop-spooler
--- a/overlay/bin/desktop-spooler
+++ b/overlay/bin/desktop-spooler
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # .SCRIPTDOC
 
@@ -14,10 +14,34 @@
 
 # .LICENSE
 
-# Copyright 2018, Charles A. Daniels
-# This software is distributed under the BSD 3-clause license. The full text
-# of this software's license may be retrieved from this URL:
-# https://github.com/charlesdaniels/dotfiles/blob/master/LICENSE
+# Copyright (c) 2018, Charles Daniels (except where otherwise noted)
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#
+# 1. Redistributions of source code must retain the above copyright notice,
+#    this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# 3. Neither the name of the copyright holder nor the names of its
+#    contributors may be used to endorse or promote products derived from
+#    this software without specific prior written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
+# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
+# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+# POSSIBILITY OF SUCH DAMAGE.
 
 # .ENDOC
 
@@ -72,6 +96,15 @@ while true ; do
 			log_msg "INFO" $DOCK_DEVICE" not found"
 		fi
 	done < "$DOCK_DEVICE_LIST"
+
+	# update backlight from webcam unconditionally every interval,
+	# if we are undocked
+	if [ "$DOCK_STATE" = "UNDOCKED" ] ; then
+		~/bin/autobacklight
+		if [ $? -ne 0 ] ; then
+			log_msg "ERROR" "autobacklight failed"
+		fi
+	fi
 
 	if [ "$DOCK_STATE" = "$PREV_DOCK_STATE" ] ; then
 		# nothing to do
