finished porting pkg commands to BASH for compatibility reasons

diff --git a/bin/bin/pkg-autoremove b/bin/bin/pkg-autoremove
--- a/bin/bin/pkg-autoremove
+++ b/bin/bin/pkg-autoremove
@@ -1,17 +1,32 @@
-#!/usr/bin/fish
+#!/bin/bash
 
 pkg-upgrade
-switch (pkg-get-manager)
-case pacaur 
-    echo "unsupported operation"
-case pacman 
-    echo "unsupported operation"
-case apt-get
-    sudo apt-get autoremove
-case aptitude 
-    echo "not yet implemented"
-case yum 
-    echo "not yet implemented"
-case brew
-    echo "unsupported operation"
-end
+
+case "$(pkg-get-manager)" in 
+    pacaur)
+        pacaur -Rs $(pacman -Qtdq) 
+        ;;
+
+    pacman)
+        sudo pacman -Rs $(pacman -Qtdq)
+        ;;
+    
+    apt-get)
+        sudo apt-get autoremove
+        ;;
+
+    aptitude)
+        echo "not yet implemented"
+        ;;
+
+    yum)
+        echo "not yet implemented"
+        ;;
+
+    brew)
+        echo "unsupported operation"
+        ;;
+    *) 
+        echo "ERROR: no known package manager available"
+        exit 1
+esac 
diff --git a/bin/bin/pkg-dist-upgrade b/bin/bin/pkg-dist-upgrade
--- a/bin/bin/pkg-dist-upgrade
+++ b/bin/bin/pkg-dist-upgrade
@@ -1,17 +1,32 @@
-#!/usr/bin/fish
+#!/bin/bash
 
 pkg-upgrade
-switch (pkg-get-manager)
-case pacaur 
-    sudo mkinitcpio -p linux
-case pacman 
-    sudo mkinitcpio -p linux
-case apt-get
-    sudo apt-get dist-upgrade
-case aptitude 
-    echo "not yet implemented"
-case yum 
-    echo "not yet implemented"
-case brew
-    echo "unsupported operation"
-end
+
+case "$(pkg-get-manager)" in 
+    pacaur)
+        sudo mkinitcpio -p linux
+        ;;
+
+    pacman)
+        sudo mkinitcpio -p linux
+        ;;
+    
+    apt-get)
+        sudo apt-get dist-upgrade
+        ;;
+
+    aptitude)
+        echo "not yet implemented"
+        ;;
+
+    yum)
+        echo "not yet implemented"
+        ;;
+
+    brew)
+        echo "unsupported operation"
+        ;;
+    *) 
+        echo "ERROR: no known package manager available"
+        exit 1
+esac 
diff --git a/bin/bin/pkg-remove b/bin/bin/pkg-remove
--- a/bin/bin/pkg-remove
+++ b/bin/bin/pkg-remove
@@ -1,17 +1,30 @@
-#!/usr/bin/fish
+#!/bin/bash
 
-switch (pkg-get-manager)
-case pacaur 
-    pacaur -R $argv
-case pacman 
-    sudo pacman -R $argv
-case apt-get
-    sudo apt-get remove $argv
-case aptitude 
-    sudo aptitude remove $argv
-case yum 
-    sudo yum remove $argv
-case brew
-    brew remove $argv
-end
+case "$(pkg-get-manager)" in 
+    pacaur)
+        pacaur -R "$@"
+        ;;
 
+    pacman)
+        sudo pacman -R "$@" 
+        ;;
+    
+    apt-get)
+        sudo apt-get remove "$@" 
+        ;;
+
+    aptitude)
+        sudo aptitude remove "$@"
+        ;;
+
+    yum)
+        sudo yum remove "$@" 
+        ;;
+
+    brew)
+        brew remove "$@"
+        ;;
+    *) 
+        echo "ERROR: no known package manager available"
+        exit 1
+esac 
diff --git a/bin/bin/pkg-search b/bin/bin/pkg-search
--- a/bin/bin/pkg-search
+++ b/bin/bin/pkg-search
@@ -1,16 +1,30 @@
-#!/usr/bin/fish
+#!/bin/bash
 
-switch (pkg-get-manager)
-case pacaur 
-    pacaur -Ss $argv
-case pacman 
-    pacman -Ss $argv
-case apt-get
-    apt-cache search $argv
-case aptitude 
-    aptitude search $argv
-case yum 
-    yum search $argv
-case brew
-    brew search $argv
-end
+case "$(pkg-get-manager)" in 
+    pacaur)
+        pacaur -Ss "$@"
+        ;;
+
+    pacman)
+        pacman -Ss "$@" 
+        ;;
+    
+    apt-get)
+        apt-cache search "$@" 
+        ;;
+
+    aptitude)
+        aptitude search "$@"
+        ;;
+
+    yum)
+        yum search "$@" 
+        ;;
+
+    brew)
+        brew search "$@"
+        ;;
+    *) 
+        echo "ERROR: no known package manager available"
+        exit 1
+esac 
diff --git a/bin/bin/pkg-update b/bin/bin/pkg-update
--- a/bin/bin/pkg-update
+++ b/bin/bin/pkg-update
@@ -1,17 +1,30 @@
-#!/usr/bin/fish
+#!/bin/bash
 
+case "$(pkg-get-manager)" in 
+    pacaur)
+        pacaur -Syy
+        ;;
 
-switch (pkg-get-manager)
-case pacaur 
-    pacaur -Syy
-case pacman 
-    sudo pacman -Syy
-case apt-get
-    sudo apt-get update
-case aptitude 
-    sudo aptitude update
-case yum 
-    sudo yum update
-case brew
-    brew update
-end
+    pacman)
+        sudo pacman -Syy
+        ;;
+    
+    apt-get)
+        sudo apt-get update 
+        ;;
+
+    aptitude)
+        sudo aptitude update
+        ;;
+
+    yum)
+        sudo yum update 
+        ;;
+
+    brew)
+        brew update
+        ;;
+    *) 
+        echo "ERROR: no known package manager available"
+        exit 1
+esac 
diff --git a/bin/bin/pkg-upgrade b/bin/bin/pkg-upgrade
--- a/bin/bin/pkg-upgrade
+++ b/bin/bin/pkg-upgrade
@@ -1,16 +1,31 @@
-#!/usr/bin/fish
+#!/bin/bash
 
-switch (pkg-get-manager)
-case pacaur 
-    pacaur -Syu
-case pacman 
-    sudo pacman -Syu
-case apt-get
-    sudo apt-get upgrade
-case aptitude 
-    sudo aptitude upgrade
-case yum 
-    sudo yum upgrade
-case brew
-    echo "unsupported operation"
-end
+pkg-update
+case "$(pkg-get-manager)" in 
+    pacaur)
+        pacaur -Syu 
+        ;;
+
+    pacman)
+        sudo pacman -Syu
+        ;;
+    
+    apt-get)
+        sudo apt-get upgrade
+        ;;
+
+    aptitude)
+        sudo aptitude upgrade
+        ;;
+
+    yum)
+        sudo yum upgrade
+        ;;
+
+    brew)
+        brew upgrade
+        ;;
+    *) 
+        echo "ERROR: no known package manager available"
+        exit 1
+esac 
