implemented sync-all

diff --git a/bin/bin/sync-all b/bin/bin/sync-all
--- a/bin/bin/sync-all
+++ b/bin/bin/sync-all
@@ -1,4 +1,15 @@
 #!/bin/bash
 
 # sync all sync targets
-echo "TODO"
+
+if [ ! -d $CAD_ETC_PATH/sync/targets ] ; then 
+    echo "ERROR: no targets found!"
+    exit 1
+fi 
+
+
+for f in $CAD_ETC_PATH/sync/targets/*.cfg ; do
+    . $f
+    $CAD_SYNC_TARGET_COMMAND "$CAD_SYNC_TARGET_OPTS" \
+        "$CAD_SYNC_TARGET_SOURCE_DIR" "$CAD_SYNC_TARGET_DEST_DIR"
+done 
