added 3 new scripts

diff --git a/universal/bin/bin/archive b/universal/bin/bin/archive
--- a/universal/bin/bin/archive
+++ b/universal/bin/bin/archive
@@ -3,10 +3,14 @@
 #
 #  OVERVIEW
 #  ========
-#  This script selects an appropriate installed package manager and performs a
-#  package upgrade operation. Before doing this, it invokes ``pkg-update`` to
-#  retrieve an up to date package listing.
+#  This script produces an archive, as well as a manifest file and checksums
+#  for both the archive and it's contents. It uses xz compression to generate
+#  the archive.
 #  
+#  USAGE
+#  =====
+#   $1 . . . . the directory to archive
+#
 ########10########20########30#### LISCENSE ####50########60########70########80
 #  Copyright (c) 2016, Charles Daniels
 #  All rights reserved.
@@ -38,41 +42,64 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #  
 ########10########20########30########40########50########60########70########80
-pkg-update
-case "$(pkg-get-manager)" in 
-  pacaur)
-    pacaur -Syu 
-    ;;
 
-  pacman)
-    sudo pacman -Syu
-    ;;
-  
-  apt-get)
-    sudo apt-get upgrade
-    ;;
 
-  aptitude)
-    sudo aptitude upgrade
-    ;;
+ARCHIVE_DIR="$1"
+TIMESTAMP="$(iso8601date)"
+TEMP_DIR=/tmp/archive-$TIMESTAMP
 
-  yum)
-    sudo yum upgrade
-    ;;
+if [ ! -d "$ARCHIVE_DIR" ] ; then
+  echo "ERROR: $ARCHIVE_DIR does not exist or is not a directory"
+  exit 1
+fi
 
-  brew)
-    brew upgrade
-    ;;
+if [ -e "$ARCHIVE_DIR.tar.xz" ] ; then
+  echo "ERROR: $ARCHIVE_DIR.tar.xz already exists"
+  exit 1
+fi
 
-  pkg)
-    sudo pkg upgrade
-    ;;
+printf "STATUS: creating workspace... "
+mkdir -p $TEMP_DIR
+echo "done"
 
-  port)
-    sudo port upgrade outdated
-    ;;
+printf "STATUS: generating md5 sums... "
+find $ARCHIVE_DIR -type f | parallel md5 {} 2> /dev/null > $TEMP_DIR/md5sums.txt
+echo "done"
 
-  *) 
-    echo "ERROR: no known package manager available"
-    exit 1
-esac 
+printf "STATUS: generating SHA sums... "
+find $ARCHIVE_DIR -type f | parallel shasum {} 2> /dev/null > $TEMP_DIR/shasums.txt
+echo "done"
+
+printf "STATUS: gathering system information... "
+sysenv > $TEMP_DIR/sysenv.txt
+echo "done"
+
+printf "STATUS: preparing archive... "
+if [ -d "$ARCHIVE_DIR/archive_info" ] ; then 
+  echo ""
+  printf "WARNING: $ARCHIVE_DIR/archive_info already exists, backing it up to ./ ..."
+  if [ -e ./archive_info.bak ] ; then 
+    echo ""
+    printf "WARNING: ./archive_info.bak already exists, deleting it..."
+    rm -rf ./archive_info
+    echo "done"
+  fi 
+  mv "$ARCHIVE_DIR/archive_info" ./archive_info.bak
+  echo "done"
+fi
+
+mkdir "$ARCHIVE_DIR/archive_info"
+cp $TEMP_DIR/*txt "$ARCHIVE_DIR/archive_info"
+echo "done"
+
+printf "STATUS: compressing archive... "
+tar cvfJ "$ARCHIVE_DIR.tar.xz" "$ARCHIVE_DIR" > "$ARCHIVE_DIR.manifest" 2>&1
+echo "done"
+
+printf "STATUS: removing workspace... "
+rm -rf $TEMP_DIR
+echo "done"
+
+printf "STATUS: removing archive info from original... "
+rm -rf "$ARCHIVE_DIR/archive_info"
+echo "done"
