rather than exiting if no clipboard manager is found, cliptool will now failover to a .txt file in /tmp

diff --git a/universal/bin/bin/cliptool b/universal/bin/bin/cliptool
--- a/universal/bin/bin/cliptool
+++ b/universal/bin/bin/cliptool
@@ -97,17 +97,18 @@ fi
 
 if (: "${CLIPTOOL_CLIPBOARD_MANAGER?}") 2>/dev/null; then
   CLIPBOARD_MANAGER="$CLIPTOOL_CLIPBOARD_MANAGER"
+  command -v "$CLIPBOARD_MANAGER" > /dev/null
+  if [ $? -ne 0 ] ; then
+    echo "ERROR 104: selected clipboard manager $CLIPBOARD_MANAGER not found"
+    exit 1
+  fi
 fi
 
 if [ "$CLIPBOARD_MANAGER" == "ERROR" ] ; then
-  echo "ERROR 59: failed to detect any installed clipboard manager"
-  exit 1
-fi
-
-command -v "$CLIPBOARD_MANAGER" > /dev/null
-if [ $? -ne 0 ] ; then
-  echo "ERROR 104: selected clipboard manager $CLIPBOARD_MANAGER not found"
-  exit 1
+  echo "WARNING 59: failed to detect any installed clipboard manager"
+  echo "INFO: failing over to temp file"
+  CLIPBOARD_MANAGER="failover"
+  touch /tmp/cliptool_clipboard.txt
 fi
 
 
@@ -134,6 +135,9 @@ case $ACTION in
       xsel)
         echo "$STDIN" | xsel -i
         ;;
+      failover)
+        echo "$STDIN" > /tmp/cliptool_clipboard.txt
+        ;;
     esac
     ;;
   get)
@@ -149,6 +153,9 @@ case $ACTION in
         ;;
       copyq)
         copyq read 0
+        ;;
+      failover)
+        cat /tmp/cliptool_clipboard.txt
         ;;
     esac
     ;;
