iadded sensible-md5 commands

diff --git a/universal/bin/bin/invoke-sensible-md5 b/universal/bin/bin/invoke-sensible-md5
--- a/universal/bin/bin/invoke-sensible-md5
+++ b/universal/bin/bin/invoke-sensible-md5
@@ -4,10 +4,7 @@
 #
 #  OVERVIEW
 #  ========
-#  This script will locate a sensible dd. It will attempt check the following
-#  
-#  * gdd
-#  * dd
+#  This script will invoke the output of sensible-md5.
 #  
 ########10########20########30#### LISCENSE ####50########60########70########80
 # Copyright (c) 2016, Charles Daniels
@@ -40,19 +37,10 @@
 # POSSIBILITY OF SUCH DAMAGE.
 ########10########20########30########40########50########60########70########80
 
-get_dd () 
-{
-  command -v $1 > /dev/null
-  if [ $? -eq 0 ] ; then
-    echo $1
-    exit
-  fi
+MD5_CMD=$(sensible-md5)
+if [ $? -ne 0 ] ; then
+  echo "ERROR 42: unable to find a sensible md5"
+  exit 1
+fi
 
-}
-
-get_dd "gdd"
-get_dd "dd"
-
-echo "ERROR: failed to locate a sensible dd"
-exit 1
-
+$MD5_CMD "$@"
