moved to new invoke terminology

diff --git a/universal/bin/bin/invoke-sensible-shell b/universal/bin/bin/invoke-sensible-shell
--- a/universal/bin/bin/invoke-sensible-shell
+++ b/universal/bin/bin/invoke-sensible-shell
@@ -4,16 +4,7 @@
 #
 #  OVERVIEW
 #  ========
-#  This script will locate a sensible shell. It will attempt to invoke a shell
-#  in the following order...
-#  
-#  * fish
-#  * bash
-#  * zsh
-#  * tcsh
-#  * csh
-#  * ksh
-#  * sh
+#  This script will invoke the output of sensible-shell.
 #  
 ########10########20########30#### LISCENSE ####50########60########70########80
 # Copyright (c) 2016, Charles Daniels
@@ -46,23 +37,10 @@
 # POSSIBILITY OF SUCH DAMAGE.
 ########10########20########30########40########50########60########70########80
 
-get_shell () 
-{
-  command -v $1 > /dev/null
-  if [ $? -eq 0 ] ; then
-    echo $1
-    exit
-  fi
+SHELL_CMD=$(sensible-shell)
+if [ $? -ne 0 ] ; then
+  echo "ERROR 42: unable to find a sensible shell"
+  exit 1
+fi
 
-}
-
-get_shell fish
-get_shell bash
-get_shell zsh
-get_shell tcsh
-get_shell csh
-get_shell ksh
-get_shell sh
-echo "ERROR: failed to locate a sensible shell"
-exit 1
-
+$SHELL_CMD
