working on making macsubl be not stupid

diff --git a/universal/bin/bin/macsubl b/universal/bin/bin/macsubl
--- a/universal/bin/bin/macsubl
+++ b/universal/bin/bin/macsubl
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/osascript
 ########10########20########30## DOCUMENTATION #50########60########70########80
 #
 #  OVERVIEW
@@ -7,12 +7,21 @@
 #  is useful, as OSX normally does not make it very easy to open .apps from
 #  the shell.
 #  
+#  Note that because of weirdness in osascript, only $1 is passed into
+#  osascript. This means globbing probably won't work. For more info, start
+#  here:
+#  https://en.wikibooks.org/wiki/AppleScript_Programming/Aliases_and_paths
+#  
 #  USAGE
 #  =====
 #  
-#    $@ . . . . passed on to sublime text
-#  
-########10########20########30#### LISCENSE ####50########60########70########80
+#    $1 . . . . the file/folder to open
+#
+########10########20########30# CONFIGURATION  #50########60########70########80
+SUBL_APP_NAME="Sublime Text"
+TARGET_PATH=$(echo "$1" | tr "/" ":")
+SCRIPT="Tell Application \"$SUBL_APP_NAME\" to open \"$TARGET_PATH\""
+########10########20########30#### LICENSE #####50########60########70########80
 #  Copyright (c) 2016, Charles Daniels
 #  All rights reserved.
 # 
@@ -44,5 +53,41 @@
 #  
 ########10########20########30########40########50########60########70########80
 
-SUBL_PATH=/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text
-nohup "$SUBL_PATH" $@ < /dev/null >/dev/null 2>&1 &
+command -v osascript > /dev/null
+if [ $? -ne 0 ] ; then
+  echo "WARNING 49: osascript is not available!"
+else
+  echo "INFO: using osascript: \"$SCRIPT\""
+  APPTAG="macsubl_$(iso8601date)"
+  temputils $APPTAG create
+  TEMP_DIR="$(temputils $APPTAG get)"
+  printf "INFO: invoking sublime text via osascript... "
+  osascript -e "$SCRIPT" > $TEMP_DIR/osascript.log 2>&1
+  if [ $? -ne 0 ] ; then
+    echo "FAIL"
+    echo "ERROR 53: osascript inovocation failed!"
+    echo "INFO: contents of $TEMP_DIR/osascript.log:"
+    cat "$TEMP_DIR/osascript.log"
+    temputils $APPTAG destroy
+    exit 1
+  else
+    echo "DONE"
+    temputils $APPTAG destroy
+    exit 0
+  fi
+fi
+
+# if we forget and use this on a Linux system, it would be nice to do something
+# useful
+command -v subl > /dev/null
+if [ $? -eq 0 ] ; then
+  subl "$@"
+  exit $?
+fi
+
+command -v subl3 > /dev/null
+if [ $? -eq 0 ] ; then
+  subl3 "$@"
+  exit $?
+fi
+
