added invoke-pdfpenpro-ocr pdf-ingest and pdf-ocr
still need to do more work on pdf-ocr to bring support for more OCR packages.
In particular, I would like to find a way for it to call into acrobat via WINE,
acrobat for OSX, and maybe tesseract.

diff --git a/universal/bin/bin/pdf-ocr b/universal/bin/bin/pdf-ocr
--- a/universal/bin/bin/pdf-ocr
+++ b/universal/bin/bin/pdf-ocr
@@ -4,13 +4,18 @@
 #  OVERVIEW
 #  ========
 #  
-#  Downloads the current weather from wttr.in . Server handles geolocation
-#  based on IP. Requires curl to be installed, and internet access for obvious
-#  reasons.
+#  Detects an appropriate OCR software on the system and attempts to OCR the
+#  given PDF and burn-in  the detected text.
 #  
-#  In case further functionality needs to be added in the future, wttr.in
-#  supports query zip codes and airport codes at `wtter.in/CODE`. Full
-#  documentation here: https://github.com/chubin/wttr.in
+#  SUPPORTED OCR SOFTWARE
+#  ======================
+#  
+#  * PDFPen Pro (6.2.1+)
+#
+#  USAGE
+#  =====
+#  
+#   $1 . . . pdf to ocr
 #    
 ########10########20########30##### LICENSE ####50########60########70########80
 #  Copyright (c) 2016, Charles Daniels
@@ -44,4 +49,43 @@
 #  
 ########10########20########30########40########50########60########70########80
 
-curl wttr.in
+TARGET_FILE="$1"
+
+
+if [ ! -f "$TARGET_FILE" ] ; then
+  echo "ERROR: target $TARGET_FILE does not exist or is not a file"
+  exit 1
+fi
+
+if [ `file $TARGET_FILE | cut -d\  -f 2` != "PDF" ] ; then
+  echo "ERROR 62: $TARGET_FILE does not seem to be a PDF"
+  exit 1
+fi
+
+
+PDFPENPRO_PATH="/Applications/PDFpenPro.app/Contents/MacOS/PDFpenPro"
+printf "INFO: detecting OCR software... "
+
+# pdfPenPro
+if [ -f "$PDFPENPRO_PATH" ] ; then
+  echo "DONE"
+  echo "INFO: detected PDFPenPro"
+  command -v invoke-pdfpenpro-ocr > /dev/null
+  if [ $? -ne 0 ] ; then
+    echo "ERROR: invoke-pdfpenpro-ocr is not in PATH"
+    exit 1
+  fi
+  printf "INFO: OCRing document... "
+  invoke-pdfpenpro-ocr `realpath $TARGET_FILE`
+  if [ $? -ne 0 ] ; then
+    echo "FAIL"
+    echo "ERROR 81: OCR failed"
+    exit 1
+  fi
+  echo "DONE"
+  exit 0
+fi
+
+echo "FAIL"
+echo "ERROR 77: no supported OCR software detected."
+exit 1
