added documentation to bin scripts, as well as liscenses

diff --git a/universal/bin/bin/pkg-autoremove b/universal/bin/bin/pkg-autoremove
--- a/universal/bin/bin/pkg-autoremove
+++ b/universal/bin/bin/pkg-autoremove
@@ -1,33 +1,74 @@
 #!/bin/sh
+########10########20########30## DOCUMENTATION #50########60########70########80
+#
+#  OVERVIEW
+#  ========
+#  This script will detect the appropriate package manager for the current
+#  system, then run an appropriate command to remove any packages which are
+#  not dependencies for any installed package. This is intended to be
+#  logically equivalent to ``apt-get autoremove`` on dpkg-based systems.
+#
+########10########20########30#### LISCENSE ####50########60########70########80
+# Copyright (c) 2016, Charles Daniels
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#
+# 1. Redistributions of source code must retain the above copyright notice,
+# this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright notice,
+# this list of conditions and the following disclaimer in the documentation
+# and/or other materials provided with the distribution.
+#
+# 3. Neither the name of the copyright holder nor the names of its
+# contributors may be used to endorse or promote products derived from this
+# software without specific prior written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
+# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
+# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+# POSSIBILITY OF SUCH DAMAGE.
+########10########20########30########40########50########60########70########80
 
-case "$(pkg-get-manager)" in 
-    pacaur)
-        pacaur -Rs $(pacaur -Qtdq) 
-        ;;
+case "$(pkg-get-manager)" in
+  pacaur)
+    pacaur -Rs $(pacaur -Qtdq)
+    ;;
 
-    pacman)
-        sudo pacman -Rs $(pacman -Qtdq)
-        ;;
-    
-    apt-get)
-        sudo apt-get autoremove
-        ;;
+  pacman)
+    sudo pacman -Rs $(pacman -Qtdq)
+    ;;
 
-    aptitude)
-        echo "not yet implemented"
-        ;;
+  apt-get)
+    sudo apt-get autoremove
+    ;;
 
-    yum)
-        echo "not yet implemented"
-        ;;
+  aptitude)
+    echo "not yet implemented"
+    ;;
 
-    brew)
-        echo "unsupported operation"
-        ;;
-	 pkg)
-	 	  sudo pkg autoremove
-		  ;;
-    *) 
-        echo "ERROR: no known package manager available"
-        exit 1
-esac 
+  yum)
+    echo "not yet implemented"
+    ;;
+
+  brew)
+    echo "unsupported operation"
+    ;;
+
+  pkg)
+    sudo pkg autoremove
+    ;;
+
+  *)
+    echo "ERROR: no known package manager available"
+    exit 1
+esac
