configure-dpms is now implemented as a single script

diff --git a/provision/overlay/bin/configure-dpms b/provision/overlay/bin/configure-dpms
--- a/provision/overlay/bin/configure-dpms
+++ b/provision/overlay/bin/configure-dpms
@@ -8,17 +8,54 @@
 # .SCRIPTDOC
 
 # Set appropriet DPMS settings for the current dock state given by
-# ~/.dspool/dock_status
+# ~/.dspool/dock_status, or by a user-provided override.
+
+# .SYNAX
+
+# $1 . . . (optional) specify DPMS configuration, one of [docked, undocked,
+#          nosleep]
 
 # .ENDOC
 
 DOCK_STATUS="$(cat ~/.dspool/dock_status)"
 if [ "$DOCK_STATUS" = "DOCKED" ] ; then
-	timestamp-message "INFO" "Configuring DPMS for docked state" > /dev/stderr
-	configure-dpms-docked
+	CONFIGURATION="docked"
 else
-	timestamp-message "INFO" "Configuring DPMS for undocked state" > /dev/stderr
-	configure-dpms-undocked
+	CONFIGURATION="undocked"
 fi
 
+# this can interfere with our settings
 killall mate-screensaver > /dev/null 2>&1 || true
+
+# if the user provided a directive, use that instead of the inferred one
+if [ $# -ge 1 ] ; then
+	CONFIGURATION="$1"
+fi
+timestamp-message "INFO" "Setting DPMS configuration to $CONFIGURATION"
+
+# not sure this does much on modern systems, but in theory it turns of the
+# bell, whatever that is.
+xset b off
+
+case "$CONFIGURATION" in
+	docked)
+		# 15 * 60 = 900
+		# 30 * 60 = 1800
+		# 45 * 60 = 2700
+		xset dpms 900 1800 2700
+		;;
+	undocked)
+		# 3 * 60 = 180
+		# 6 * 60 = 360
+		# 9 * 60 = 540
+		xset dpms 180 360 540
+		;;
+	nosleep)
+		timestamp-message "INFO" "monitor will never sleep, remember to re-enable sleep when you are done"
+		xset dpms 0 0 0
+		;;
+	*)
+		timestamp-message "ERROR" "Invalid DPMS configuration '$CONFIGURATION'"
+		exit 1
+		;;
+esac
